region: ap-northeast-1
cluster: redash
service: ecscompose-service-redash_create_db
task_definition: ecs-task-def.json
timeout: 10m0s
plugins:
  - name: tfstate
    config:
      url: s3://hi1280-tfstate-main/redash.tfstate